<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingSystem.Backtesting.Bot8012.Reporting\TradingSystem.Backtesting.Bot8012.Reporting.csproj" />
    <ProjectReference Include="..\TradingSystem.Backtesting.Bot8012\TradingSystem.Backtesting.Bot8012.csproj" />
  </ItemGroup>

</Project>
