using Dapper;using TradingSystem.Persistence.PostgreSql.Connections;
namespace TradingSystem.Persistence.PostgreSql.TradingHistory;
public sealed class TradingHistoryQueryService(ITradingDbConnectionFactory factory):ITradingHistoryQueryService
{
 public Task<IReadOnlyCollection<SignalListItem>> GetRecentSignalsAsync(string? bot, string? env, int limit, CancellationToken ct) => Query<SignalListItem>("""SELECT signal_id SignalId, bot_name BotName, strategy_version StrategyVersion, symbol Symbol, side Side, source Source, environment Environment, signal_time_utc SignalTimeUtc, reference_price ReferencePrice, reason Reason FROM trading_history.signals WHERE (@Bot IS NULL OR bot_name = @Bot) AND (@Env IS NULL OR environment = @Env) ORDER BY signal_time_utc DESC LIMIT @Limit;""", new{Bot = bot, Env = env, Limit = Math.Clamp(limit, 1, 1000)}, ct);
 public async Task<TradingSummary> GetSummaryAsync(string bot, string env, DateTime from, DateTime to, CancellationToken ct){const string sql = """WITH d AS(SELECT signal_id, bool_or(decision = 'Open') opened, bool_or(decision = 'Block') blocked FROM trading_history.strategy_decisions GROUP BY signal_id), p AS(SELECT signal_id, count(*) positions, count(*) FILTER(WHERE status = 'Closed') closed, coalesce(sum(realized_pnl) FILTER(WHERE status = 'Closed'), 0) pnl FROM trading_history.positions GROUP BY signal_id) SELECT count(*) Signals, count(*) FILTER(WHERE d.opened) OpenDecisions, count(*) FILTER(WHERE d.blocked) BlockedDecisions, coalesce(sum(p.positions), 0) Positions, coalesce(sum(p.closed), 0) ClosedPositions, coalesce(sum(p.pnl), 0) RealizedPnl FROM trading_history.signals s LEFT JOIN d ON d.signal_id = s.signal_id LEFT JOIN p ON p.signal_id = s.signal_id WHERE s.bot_name = @Bot AND s.environment = @Env AND s.signal_time_utc>=@From AND s.signal_time_utc<@To;""";await using var c = await factory.OpenAsync(ct);return await c.QuerySingleAsync<TradingSummary>(new CommandDefinition(sql, new{Bot = bot, Env = env, From = from, To = to}, commandTimeout:factory.CommandTimeoutSeconds, cancellationToken:ct));}
 public Task<IReadOnlyCollection<BlockReasonSummary>> GetBlockReasonsAsync(string bot, string env, DateTime from, DateTime to, CancellationToken ct) => Query<BlockReasonSummary>("""SELECT coalesce(reason, 'Unknown') Reason, count(*) Count FROM trading_history.strategy_decisions WHERE bot_name = @Bot AND environment = @Env AND decision = 'Block' AND decided_at_utc>=@From AND decided_at_utc<@To GROUP BY coalesce(reason, 'Unknown') ORDER BY Count DESC;""", new{Bot = bot, Env = env, From = from, To = to}, ct);
 async Task<IReadOnlyCollection<T>> Query<T>(string sql, object args, CancellationToken ct){await using var c = await factory.OpenAsync(ct);var rows = await c.QueryAsync<T>(new CommandDefinition(sql, args, commandTimeout:factory.CommandTimeoutSeconds, cancellationToken:ct));return rows.AsList();}
}
