<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TradingSystem.Domain\TradingSystem.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Bots\" />
    <Folder Include="Notifications\" />
    <Folder Include="Strategires\" />
    <Folder Include="Risk\" />
    <Folder Include="Orders\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
