CREATE SCHEMA IF NOT EXISTS trading_history;
CREATE TABLE IF NOT EXISTS trading_history.signals(signal_id text PRIMARY KEY, bot_name text NOT NULL, strategy_version text NOT NULL, symbol text NOT NULL, side text NOT NULL, source text NOT NULL, environment text NOT NULL, signal_time_utc timestamptz NOT NULL, reference_price numeric NULL, candle_open_time_utc timestamptz NULL, interval text NULL, reason text NULL, raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS trading_history.strategy_decisions(id bigserial PRIMARY KEY, signal_id text NOT NULL, bot_name text NOT NULL, strategy_version text NOT NULL, symbol text NOT NULL, side text NOT NULL, decision text NOT NULL, reason text NULL, environment text NOT NULL, decided_at_utc timestamptz NOT NULL, mark_price numeric NULL, parameters jsonb NOT NULL DEFAULT '{}'::jsonb, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS trading_history.positions(position_id text PRIMARY KEY, signal_id text NULL, bot_name text NOT NULL, strategy_version text NOT NULL, symbol text NOT NULL, side text NOT NULL, source text NULL, environment text NOT NULL, status text NOT NULL, quantity numeric NOT NULL, entry_price numeric NULL, take_profit_price numeric NULL, opened_at_utc timestamptz NOT NULL, closed_at_utc timestamptz NULL, realized_pnl numeric NULL, fees numeric NULL, close_reason text NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS trading_history.position_events(id bigserial PRIMARY KEY, position_id text NOT NULL, bot_name text NOT NULL, event_type text NOT NULL, status text NULL, occurred_at_utc timestamptz NOT NULL, price numeric NULL, quantity numeric NULL, details jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE TABLE IF NOT EXISTS trading_history.order_events(event_key text PRIMARY KEY, bot_name text NOT NULL, position_id text NULL, client_order_id text NULL, exchange_order_id text NULL, order_type text NULL, status text NULL, side text NULL, symbol text NULL, environment text NOT NULL, occurred_at_utc timestamptz NOT NULL, price numeric NULL, quantity numeric NULL, executed_quantity numeric NULL, raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb);
CREATE INDEX IF NOT EXISTS ix_signals_bot_time ON trading_history.signals(bot_name, environment, signal_time_utc DESC);
CREATE INDEX IF NOT EXISTS ix_decisions_bot_time ON trading_history.strategy_decisions(bot_name, environment, decided_at_utc DESC);
CREATE INDEX IF NOT EXISTS ix_positions_bot_status ON trading_history.positions(bot_name, environment, status);
