<Project Sdk = "Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
	</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include = "../TradingSystem.Dashboard.Contracts/TradingSystem.Dashboard.Contracts.csproj" />
    <ProjectReference Include = "../TradingSystem.Domain/TradingSystem.Domain.csproj" />
      <ProjectReference Include = "../TradingSystem.Backtesting.Bots/TradingSystem.Backtesting.Bots.csproj" />
  </ItemGroup>
</Project>
