using TradingSystem.Backtesting.Bots.Common;using TradingSystem.Backtesting.Models;using TradingSystem.Domain.Enums;using TradingSystem.Domain.MarketData;using TradingSystem.Strategies.Grid;
namespace TradingSystem.Backtesting.Bots.Common;
public interface ITpOnlyGridBacktestOptions{string BotName{ get; }string Symbol{ get; }decimal InitialBalance{ get; }decimal Quantity{ get; }int Leverage{ get; }decimal PriceDistance{ get; }decimal ProfitDistance{ get; }int OrderSideLimit{ get; }int CooldownSeconds{ get; }bool EnableLong{ get; }bool EnableShort{ get; }decimal EntryFeeRate{ get; }decimal ExitFeeRate{ get; }decimal SlippageBasisPoints{ get; }decimal TickSize{ get; }bool ForceCloseAtEnd{ get; }}
public sealed class TpOnlyGridBacktestEngine(GridSpacingPolicy policy)
{
 public BotBacktestResult<TOptions> Run<TOptions>(IReadOnlyList<MarketCandle> sourceCandles, IReadOnlyList<HistoricalBotSignal> sourceSignals, TOptions o) where TOptions:ITpOnlyGridBacktestOptions
 {
  if(sourceCandles.Count<2)throw new InvalidOperationException("At least two candles are required.");
  var candles = sourceCandles.OrderBy(x => x.OpenTimeUtc).ToArray();var signals = sourceSignals.OrderBy(x => x.TimeUtc).ToArray();var active = new List<P>();var completed = new List<BotPositionResult>();var executions = new List<BotExecution>();var decisions = new List<BotSignalDecision>();var equity = new List<BotEquityPoint>();var last = new Dictionary<TradeSide, DateTime>();decimal balance = o.InitialBalance, peak = balance;var si = 0;
  foreach(var c in candles){while(si<signals.Length && signals[si].TimeUtc<=c.OpenTimeUtc){var s = signals[si++];var ps = ToPositionSide(s.Side);if((s.Side==TradeSide.Long && !o.EnableLong) || (s.Side==TradeSide.Short && !o.EnableShort)){decisions.Add(new(s.TimeUtc, s.Side, "Block", "SIDE_DISABLED", c.Open, s.SignalId));continue;}if(last.TryGetValue(s.Side, out var at) && s.TimeUtc-at<TimeSpan.FromSeconds(o.CooldownSeconds)){decisions.Add(new(s.TimeUtc, s.Side, "Block", "SIGNAL_COOLDOWN", c.Open, s.SignalId));continue;}var refs = active.Select(x => new GridPositionReference(ToPositionSide(x.Side), x.Tp, x.EntryTime)).ToArray();var check = policy.Evaluate(ps, c.Open, refs, new(o.PriceDistance, o.ProfitDistance, o.OrderSideLimit));decisions.Add(new(s.TimeUtc, s.Side, check.Allowed?"Open":"Block", check.Reason, c.Open, s.SignalId));if(!check.Allowed)continue;var entry = BotBacktestMath.RoundToStep(BotBacktestMath.EntrySlippage(c.Open, s.Side, o.SlippageBasisPoints), o.TickSize);var margin = entry*o.Quantity/o.Leverage;if(margin>balance){decisions.Add(new(s.TimeUtc, s.Side, "Block", "INSUFFICIENT_MARGIN", entry, s.SignalId));continue;}var tp = BotBacktestMath.RoundToStep(s.Side==TradeSide.Long?entry+o.ProfitDistance:entry-o.ProfitDistance, o.TickSize);var fee = entry*o.Quantity*o.EntryFeeRate;balance-=fee;var p = new P(Guid.NewGuid().ToString("N")[..8], s.Side, c.OpenTimeUtc, entry, tp, o.Quantity, fee);active.Add(p);executions.Add(new(p.Id, c.OpenTimeUtc, "ENTRY", p.Side, entry, p.Qty, 0, fee, s.Source));last[s.Side] = s.TimeUtc;}
   foreach(var p in active.ToArray()){var hit = p.Side==TradeSide.Long?c.High>=p.Tp:c.Low<=p.Tp;if(hit)Close(p, p.Tp, c.CloseTimeUtc, "TAKE_PROFIT");}
   var unreal = active.Sum(x => BotBacktestMath.UnrealizedPnl(x.Side, x.Entry, c.Close, x.Qty));var eq = balance+unreal;peak = Math.Max(peak, eq);var dd = peak-eq;equity.Add(new(c.CloseTimeUtc, balance, eq, peak, dd, peak==0?0:dd/peak*100m));}
  if(o.ForceCloseAtEnd){var c = candles[^1];foreach(var p in active.ToArray())Close(p, BotBacktestMath.ExitSlippage(c.Close, p.Side, o.SlippageBasisPoints), c.CloseTimeUtc, "BACKTEST_END");}
  return new(){RunId = $"{o.BotName}_{o.Symbol}_{DateTime.UtcNow:yyyyMMdd_HHmmssfff}", BotName = o.BotName, Options = o, StartedAtUtc = candles[0].OpenTimeUtc, CompletedAtUtc = DateTime.UtcNow, Metrics = BotBacktestMath.Metrics(signals.Length, decisions.Count(x => x.Decision=="Block"), o.InitialBalance, balance, completed, equity), Positions = completed, Executions = executions, Decisions = decisions, EquityCurve = equity, Candles = candles, Signals = signals};
  void Close(P p, decimal raw, DateTime time, string reason){var price = BotBacktestMath.RoundToStep(raw, o.TickSize);var gross = BotBacktestMath.UnrealizedPnl(p.Side, p.Entry, price, p.Qty);var fee = price*p.Qty*o.ExitFeeRate;balance+=gross-fee;active.Remove(p);executions.Add(new(p.Id, time, "EXIT", p.Side, price, p.Qty, gross, fee, reason));completed.Add(new(){PositionId = p.Id, Side = p.Side, EntryTimeUtc = p.EntryTime, EntryPrice = p.Entry, ExitTimeUtc = time, ExitPrice = price, Quantity = p.Qty, GrossPnl = gross, Fees = p.EntryFee+fee, NetPnl = gross-p.EntryFee-fee, ExitReason = reason, PartialTakeProfitReached = false});}
 }
 private static PositionSide ToPositionSide(TradeSide s) => s==TradeSide.Long?PositionSide.Long:PositionSide.Short;
 private sealed record P(string Id, TradeSide Side, DateTime EntryTime, decimal Entry, decimal Tp, decimal Qty, decimal EntryFee);
}