<Project Sdk = "Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include = "../TradingSystem.Application/TradingSystem.Application.csproj"/><ProjectReference Include = "../TradingSystem.Domain/TradingSystem.Domain.csproj"/><PackageReference Include = "Microsoft.Extensions.DependencyInjection.Abstractions" Version = "8.0.2"/><PackageReference Include = "Microsoft.Extensions.Options" Version = "8.0.2"/><PackageReference Include = "Microsoft.Extensions.Options.ConfigurationExtensions" Version = "8.0.0"/></ItemGroup></Project>