using Microsoft.Extensions.Options;using TradingSystem.Application.MarketData;using TradingSystem.JobOrchestration;
namespace TradingSystem.Jobs.Worker.Workers;
public sealed class HistoricalDataIngestionWorker(IHistoricalCandleRangeSource source, IHistoricalMarketDataStore store, IOptions<HistoricalDataIngestionOptions> options, ILogger<HistoricalDataIngestionWorker> logger):BackgroundService
{
 protected override async Task ExecuteAsync(CancellationToken ct){var o = options.Value;if(!o.Enabled)return;using var timer = new PeriodicTimer(TimeSpan.FromMinutes(Math.Max(1, o.PollMinutes)));do{foreach(var symbol in o.Symbols)foreach(var interval in o.Intervals)try{await Ingest(symbol, interval, o, ct);}catch(Exception ex){logger.LogError(ex, "Historical ingestion failed for {Symbol} {Interval}", symbol, interval);}}while(await timer.WaitForNextTickAsync(ct));}
 private async Task Ingest(string symbol, string interval, HistoricalDataIngestionOptions o, CancellationToken ct){var duration = ParseInterval(interval);var latest = await store.GetLatestOpenTimeAsync(symbol, interval, ct);var from = latest?.Subtract(TimeSpan.FromTicks(duration.Ticks*Math.Max(1, o.OverlapCandles)))??DateTime.UtcNow.AddDays(-o.InitialLookbackDays);var to = DateTime.UtcNow;var candles = await source.LoadAsync(symbol, interval, from, to, ct);await store.UpsertCandlesAsync(candles, ct);var all = await store.LoadCandlesAsync(symbol, interval, from, to, ct);var gaps = DetectGaps(symbol, interval, all, duration);await store.ReplaceGapsAsync(symbol, interval, gaps, ct);logger.LogInformation("Historical data {Symbol} {Interval}: upserted {Count},  gaps {Gaps}", symbol, interval, candles.Count, gaps.Count);}
 public static IReadOnlyList<HistoricalDataGap> DetectGaps(string symbol, string interval, IReadOnlyList<TradingSystem.Domain.MarketData.MarketCandle> candles, TimeSpan duration){var gaps = new List<HistoricalDataGap>();for(var i = 1;i<candles.Count;i++){var expected = candles[i-1].OpenTimeUtc+duration;if(candles[i].OpenTimeUtc<=expected)continue;var missing = (int)((candles[i].OpenTimeUtc-expected).Ticks/duration.Ticks);gaps.Add(new(symbol, interval, expected, candles[i].OpenTimeUtc-duration, missing));}return gaps;}
 public static TimeSpan ParseInterval(string value){var unit = value[^1];var amount = int.Parse(value[..^1]);return unit switch{'m' => TimeSpan.FromMinutes(amount), 'h' => TimeSpan.FromHours(amount), 'd' => TimeSpan.FromDays(amount), _ => throw new ArgumentOutOfRangeException(nameof(value), "Supported intervals use m,  h or d.")};}
}
