using Microsoft.Extensions.DependencyInjection;using System.Text.Json;using System.Text.Json.Nodes;using TradingSystem.Analytics.Abstractions;using TradingSystem.Analytics.Models;using TradingSystem.Backtesting.Bots.Bot8011;using TradingSystem.Backtesting.Bots.Bot8012;using TradingSystem.Backtesting.Bots.Bot8013;using TradingSystem.Backtesting.Bots.Bot8014;using TradingSystem.Backtesting.Bots.Bot8015;using TradingSystem.Backtesting.Bots.Bot8016;using TradingSystem.Backtesting.Bots.Common;using TradingSystem.Backtesting.Bots.Signals;using TradingSystem.Dashboard.Contracts;using TradingSystem.JobOrchestration;using TradingSystem.Optimization.Analytics;
namespace TradingSystem.Jobs.Worker.Execution;
public sealed class BacktestExecutionService(IServiceProvider services, IHistoricalMarketDataStore market, IHistoricalSignalStore signalStore, IPerformanceAnalyticsStore analytics)
{
 public async Task<Guid> ExecuteAsync(BacktestRequest request, string interval, CancellationToken ct){if(await market.HasGapsAsync(request.Symbol, interval, request.FromUtc, request.ToUtc, ct))throw new InvalidOperationException("Historical data contains unresolved candle gaps for the requested period.");var candles = await market.LoadCandlesAsync(request.Symbol, interval, request.FromUtc, request.ToUtc, ct);if(candles.Count<2)throw new InvalidOperationException("Historical candles are missing for the requested period.");var signals = request.SignalSource.Equals("Internal", StringComparison.OrdinalIgnoreCase)?new EmaCrossDemoSignalSource().Generate(candles):await signalStore.LoadAsync(request.BotName, request.Symbol, request.FromUtc, request.ToUtc, ct);if(signals.Count==0)throw new InvalidOperationException("No historical signals were found for the requested source and period.");return request.BotName.ToUpperInvariant() switch{
 "BOT8011" => await RunAsync(await Get<Bot8011BacktestEngine>().RunAsync(request.InitialBalance, Options(new Bot8011BacktestOptions{Symbol = request.Symbol}, request.Parameters), candles, signals), "1.0.0", interval, ct), 
 "BOT8012" => await RunAsync(Get<Bot8012BacktestEngine>().Run(candles, signals, Options(new Bot8012BacktestOptions{Symbol = request.Symbol, InitialBalance = request.InitialBalance, EntryFeeRate = request.CommissionPercent/100m, ExitFeeRate = request.CommissionPercent/100m, SlippageBasisPoints = request.SlippagePercent*100m}, request.Parameters)), "1.0.0", interval, ct), 
 "BOT8013" => await RunAsync(Get<Bot8013BacktestEngine>().Run(candles, signals, Options(new Bot8013BacktestOptions{Symbol = request.Symbol, InitialBalance = request.InitialBalance}, request.Parameters)), "1.0.0", interval, ct), 
 "BOT8014" => await RunAsync(Get<Bot8014BacktestEngine>().Run(candles, signals, Options(new Bot8014BacktestOptions{Symbol = request.Symbol, InitialBalance = request.InitialBalance}, request.Parameters)), "1.0.0", interval, ct), 
 "BOT8015" => await RunAsync(await Get<Bot8015BacktestEngine>().RunAsync(candles, signals, Options(new Bot8015BacktestOptions{Symbol = request.Symbol, InitialBalance = request.InitialBalance}, request.Parameters)), "1.0.0", interval, ct), 
 "BOT8016" => await RunAsync(Get<Bot8016BacktestEngine>().Run(candles, BuildIndicators(candles), Options(new Bot8016BacktestOptions{Symbol = request.Symbol, EntryTimeframe = interval, ExitTimeframe = interval, InitialBalance = request.InitialBalance}, request.Parameters)), "1.0.0", interval, ct), 
 _ => throw new ArgumentOutOfRangeException(nameof(request.BotName), "Supported bots are BOT8011-BOT8016.")};}
 private T Get<T>() where T:notnull => services.GetRequiredService<T>();
 private async Task<Guid> RunAsync<T>(BotBacktestResult<T> result, string version, string interval, CancellationToken ct){var mapped = BacktestPerformanceMapper.Map(result, version, interval);await analytics.CreateRunAsync(mapped.Run, ct);await analytics.SaveSnapshotAsync(mapped.Snapshot, ct);await analytics.SaveTradesAsync(mapped.Run.RunId, mapped.Trades, ct);return mapped.Run.RunId;}
 private static T Options<T>(T seed, IReadOnlyDictionary<string, string> values){var json = JsonSerializer.SerializeToNode(seed)!.AsObject();foreach(var pair in values){var key = json.Select(x => x.Key).FirstOrDefault(x => x.Equals(pair.Key, StringComparison.OrdinalIgnoreCase));if(key is null)continue;json[key] = JsonValue.Create(pair.Value);}return JsonSerializer.Deserialize<T>(json.ToJsonString(), new JsonSerializerOptions{PropertyNameCaseInsensitive = true, NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowReadingFromString})!;}
 private static IReadOnlyList<HistoricalAlligatorSnapshot> BuildIndicators(IReadOnlyList<TradingSystem.Domain.MarketData.MarketCandle> candles){var rows = new List<HistoricalAlligatorSnapshot>(candles.Count);for(var i = 0;i<candles.Count;i++){var start = Math.Max(0, i-199);var avg = candles.Skip(start).Take(i-start+1).Average(x => x.Close);rows.Add(new(candles[i].CloseTimeUtc, candles[i].Symbol, candles[i].Interval, avg, avg, avg, avg));}return rows;}
}
