<Project Sdk = "Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
	</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include = "../TradingSystem.Backtesting.Bots/TradingSystem.Backtesting.Bots.csproj" />
    <ProjectReference Include = "../TradingSystem.Analytics/TradingSystem.Analytics.csproj" />
  </ItemGroup>
</Project>
